# Generated by Django 4.2.4 on 2023-08-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0002_remove_user_gdr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_type',
            field=models.CharField(choices=[('customer', 'customer'), ('Community Manager', 'Community Manager'), ('Service provider', 'Service provider')], default='customer', max_length=20),
        ),
    ]
