# Generated by Django 4.2.4 on 2023-08-28 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0006_customer_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_type',
            field=models.CharField(choices=[('customer', 'customer'), ('Service provider', 'Service provider')], default='customer', max_length=20),
        ),
    ]
