# Generated by Django 4.2.4 on 2023-08-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0007_alter_order_customer_alter_user_role_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfimg',
            field=models.ImageField(default='profile.png', upload_to='Profiles/'),
        ),
    ]
