# Generated by Django 4.2.4 on 2023-08-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0008_user_pfimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfimg',
            field=models.ImageField(default='profile.png', upload_to='images/'),
        ),
    ]
