# Generated by Django 4.2.4 on 2023-08-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0017_customer_order_orderitem_shippingaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_type',
            field=models.CharField(choices=[('customer', 'customer'), ('Service provider', 'Service provider')], default='customer', max_length=30),
        ),
    ]
