# Generated by Django 4.2.4 on 2023-08-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0024_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
