# Generated by Django 4.2.4 on 2023-08-31 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0025_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
    ]
