# Generated by Django 4.2.4 on 2023-08-31 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0027_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street_address',
            new_name='flat_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='postal_code',
        ),
    ]
