# Generated by Django 4.2.4 on 2023-09-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0028_rename_street_address_address_flat_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_type',
            field=models.CharField(choices=[('0', 'Eletric Service'), ('1', 'AC Service'), ('2', 'None'), ('3', 'Carpentering')], default='2', max_length=25),
        ),
    ]
