# Generated by Django 4.2.4 on 2023-09-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0030_alter_product_image_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='field_type',
            field=models.CharField(choices=[('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Carpenter', 'Carpenter'), ('None', 'None')], default='None', max_length=30),
        ),
    ]
