# Generated by Django 4.2.4 on 2023-09-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0031_alter_service_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
