# Generated by Django 4.2.4 on 2023-09-02 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0033_approvals'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocatedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMSApp.order')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMSApp.service')),
            ],
        ),
    ]
