# Generated by Django 4.2.4 on 2023-09-02 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0034_allocatedorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pfimg',
        ),
    ]
