# Generated by Django 4.2.4 on 2023-09-03 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0036_reviewandrating_order_total_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewandRating',
        ),
    ]
