# Generated by Django 4.2.4 on 2023-09-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0038_reviewandrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='field_type',
            field=models.CharField(choices=[('Electrician', 'Electrician'), ('AC Technician', 'AC Technician'), ('Carpenter', 'Carpenter'), ('None', 'None')], default='None', max_length=30),
        ),
    ]
