# Generated by Django 4.2.4 on 2023-09-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0040_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatedorder',
            name='chosen_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
