# Generated by Django 4.2.4 on 2023-09-08 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0041_allocatedorder_chosen_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewandrating',
            name='order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='SMSApp.order'),
        ),
    ]
