# Generated by Django 4.2.4 on 2023-09-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0042_reviewandrating_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
