# Generated by Django 4.2.4 on 2023-09-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0044_reviewandrating_allo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewandrating',
            name='allo',
        ),
    ]
