# Generated by Django 4.2.4 on 2023-09-10 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0045_remove_reviewandrating_allo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewandrating',
            name='allo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='SMSApp.allocatedorder'),
        ),
    ]
