# Generated by Django 4.2.4 on 2023-09-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0047_alter_service_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='form',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
